/*
 * generated by Xtext
 */
package de.fraunhofer.iem.reqpat.core.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import de.fraunhofer.iem.reqpat.core.ui.internal.ReqPatActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ReqPatExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ReqPatActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ReqPatActivator.getInstance().getInjector(ReqPatActivator.DE_FRAUNHOFER_IEM_REQPAT_CORE_REQPAT);
	}
	
}
