/*
 * generated by Xtext
 */
package de.fraunhofer.iem.reqpat.core;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ReqPatRuntimeModule extends de.fraunhofer.iem.reqpat.core.AbstractReqPatRuntimeModule {

}
