/*
 * generated by Xtext
 */
package de.fraunhofer.iem.reqpat.core.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ReqPatUiModule extends de.fraunhofer.iem.reqpat.core.ui.AbstractReqPatUiModule {
	public ReqPatUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
