/*
* generated by Xtext
*/
package de.fraunhofer.iem.reqpat.core.ui.contentassist;

import de.fraunhofer.iem.reqpat.core.ui.contentassist.AbstractReqPatProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class ReqPatProposalProvider extends AbstractReqPatProposalProvider {

}
