/*
 * generated by Xtext
 */
package de.fraunhofer.iem.reqpat.demo.validation;
 
import java.util.ArrayList;
import java.util.List;

import org.eclipse.emf.ecore.EPackage;

public class AbstractReqPatDemoJavaValidator extends de.fraunhofer.iem.reqpat.core.validation.ReqPatJavaValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://de.fraunhofer.iem.reqpat.core.model"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://de.fraunhofer.iem.reqpat.demo.model"));
		return result;
	}

}
