/*
* generated by Xtext
*/
package de.fraunhofer.iem.reqpat.core.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ReqPatAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("de/fraunhofer/iem/reqpat/core/parser/antlr/internal/InternalReqPat.tokens");
	}
}
