/*
* generated by Xtext
*/
package de.fraunhofer.iem.reqpat.core.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import de.fraunhofer.iem.reqpat.core.services.ReqPatGrammarAccess;

public class ReqPatParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ReqPatGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected de.fraunhofer.iem.reqpat.core.parser.antlr.internal.InternalReqPatParser createParser(XtextTokenStream stream) {
		return new de.fraunhofer.iem.reqpat.core.parser.antlr.internal.InternalReqPatParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Root";
	}
	
	public ReqPatGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ReqPatGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
