/*
 * generated by Xtext
 */
package de.fraunhofer.iem.reqpat.demo.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import de.fraunhofer.iem.reqpat.demo.services.ReqPatDemoGrammarAccess;

public class ReqPatDemoParser extends AbstractContentAssistParser {
	
	@Inject
	private ReqPatDemoGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected de.fraunhofer.iem.reqpat.demo.ui.contentassist.antlr.internal.InternalReqPatDemoParser createParser() {
		de.fraunhofer.iem.reqpat.demo.ui.contentassist.antlr.internal.InternalReqPatDemoParser result = new de.fraunhofer.iem.reqpat.demo.ui.contentassist.antlr.internal.InternalReqPatDemoParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getRequirementPatternAccess().getAlternatives_0(), "rule__RequirementPattern__Alternatives_0");
					put(grammarAccess.getTheAnalysisFunctionAccess().getAlternatives_1(), "rule__TheAnalysisFunction__Alternatives_1");
					put(grammarAccess.getTheFollowingInformationAccess().getAlternatives_1(), "rule__TheFollowingInformation__Alternatives_1");
					put(grammarAccess.getSpecObjAccess().getAlternatives_1(), "rule__SpecObj__Alternatives_1");
					put(grammarAccess.getRootAccess().getGroup(), "rule__Root__Group__0");
					put(grammarAccess.getRequirementPatternAccess().getGroup(), "rule__RequirementPattern__Group__0");
					put(grammarAccess.getTheAnalysisFunctionAccess().getGroup(), "rule__TheAnalysisFunction__Group__0");
					put(grammarAccess.getTheFollowingInformationAccess().getGroup(), "rule__TheFollowingInformation__Group__0");
					put(grammarAccess.getAnalysisFunctionDefAccess().getGroup(), "rule__AnalysisFunctionDef__Group__0");
					put(grammarAccess.getAnalysisFunctionPurpAccess().getGroup(), "rule__AnalysisFunctionPurp__Group__0");
					put(grammarAccess.getFunctionalDeviceDefAccess().getGroup(), "rule__FunctionalDeviceDef__Group__0");
					put(grammarAccess.getFunctionalDeviceAccess().getGroup(), "rule__FunctionalDevice__Group__0");
					put(grammarAccess.getSubAnalysisFunctionDefAccess().getGroup(), "rule__SubAnalysisFunctionDef__Group__0");
					put(grammarAccess.getSubAnalysisFunctionAccess().getGroup(), "rule__SubAnalysisFunction__Group__0");
					put(grammarAccess.getIncomingInformationDefAccess().getGroup(), "rule__IncomingInformationDef__Group__0");
					put(grammarAccess.getIncomingInformationDefAccess().getGroup_3(), "rule__IncomingInformationDef__Group_3__0");
					put(grammarAccess.getIncomingInformationDefAccess().getGroup_6(), "rule__IncomingInformationDef__Group_6__0");
					put(grammarAccess.getOutgoingInformationDefAccess().getGroup(), "rule__OutgoingInformationDef__Group__0");
					put(grammarAccess.getOutgoingInformationDefAccess().getGroup_3(), "rule__OutgoingInformationDef__Group_3__0");
					put(grammarAccess.getOutgoingInformationDefAccess().getGroup_6(), "rule__OutgoingInformationDef__Group_6__0");
					put(grammarAccess.getInformationUsageAccess().getGroup(), "rule__InformationUsage__Group__0");
					put(grammarAccess.getInformationUsageAccess().getGroup_5(), "rule__InformationUsage__Group_5__0");
					put(grammarAccess.getInformationCreationAccess().getGroup(), "rule__InformationCreation__Group__0");
					put(grammarAccess.getInformationCreationAccess().getGroup_5(), "rule__InformationCreation__Group_5__0");
					put(grammarAccess.getAnalysisFunctionAccess().getGroup(), "rule__AnalysisFunction__Group__0");
					put(grammarAccess.getInformationAccess().getGroup(), "rule__Information__Group__0");
					put(grammarAccess.getSpecObjAccess().getGroup(), "rule__SpecObj__Group__0");
					put(grammarAccess.getHeadingSOAccess().getGroup(), "rule__HeadingSO__Group__0");
					put(grammarAccess.getHeadingSOAccess().getGroup_7(), "rule__HeadingSO__Group_7__0");
					put(grammarAccess.getReqPatSOAccess().getGroup(), "rule__ReqPatSO__Group__0");
					put(grammarAccess.getReqPatSOAccess().getGroup_7(), "rule__ReqPatSO__Group_7__0");
					put(grammarAccess.getFreeTextSOAccess().getGroup(), "rule__FreeTextSO__Group__0");
					put(grammarAccess.getFreeTextSOAccess().getGroup_7(), "rule__FreeTextSO__Group_7__0");
					put(grammarAccess.getRootAccess().getSpecObjectsAssignment_1(), "rule__Root__SpecObjectsAssignment_1");
					put(grammarAccess.getAnalysisFunctionDefAccess().getAnalysisFunctionAssignment_2(), "rule__AnalysisFunctionDef__AnalysisFunctionAssignment_2");
					put(grammarAccess.getAnalysisFunctionPurpAccess().getAnalysisFunctionAssignment_1(), "rule__AnalysisFunctionPurp__AnalysisFunctionAssignment_1");
					put(grammarAccess.getAnalysisFunctionPurpAccess().getPurposeAssignment_3(), "rule__AnalysisFunctionPurp__PurposeAssignment_3");
					put(grammarAccess.getFunctionalDeviceDefAccess().getFunctionalDeviceAssignment_2(), "rule__FunctionalDeviceDef__FunctionalDeviceAssignment_2");
					put(grammarAccess.getFunctionalDeviceAccess().getNameAssignment_1(), "rule__FunctionalDevice__NameAssignment_1");
					put(grammarAccess.getFunctionalDeviceAccess().getPurposeAssignment_3(), "rule__FunctionalDevice__PurposeAssignment_3");
					put(grammarAccess.getSubAnalysisFunctionDefAccess().getAnalysisFunctionAssignment_1(), "rule__SubAnalysisFunctionDef__AnalysisFunctionAssignment_1");
					put(grammarAccess.getSubAnalysisFunctionAccess().getNameAssignment_1(), "rule__SubAnalysisFunction__NameAssignment_1");
					put(grammarAccess.getSubAnalysisFunctionAccess().getParentAnalysisFunctionAssignment_3(), "rule__SubAnalysisFunction__ParentAnalysisFunctionAssignment_3");
					put(grammarAccess.getIncomingInformationDefAccess().getAnalysisFunctionAssignment_2(), "rule__IncomingInformationDef__AnalysisFunctionAssignment_2");
					put(grammarAccess.getIncomingInformationDefAccess().getFunctionalDeviceAssignment_3_1(), "rule__IncomingInformationDef__FunctionalDeviceAssignment_3_1");
					put(grammarAccess.getIncomingInformationDefAccess().getInformationListAssignment_5(), "rule__IncomingInformationDef__InformationListAssignment_5");
					put(grammarAccess.getIncomingInformationDefAccess().getInformationListAssignment_6_1(), "rule__IncomingInformationDef__InformationListAssignment_6_1");
					put(grammarAccess.getOutgoingInformationDefAccess().getAnalysisFunctionAssignment_2(), "rule__OutgoingInformationDef__AnalysisFunctionAssignment_2");
					put(grammarAccess.getOutgoingInformationDefAccess().getFunctionalDeviceAssignment_3_1(), "rule__OutgoingInformationDef__FunctionalDeviceAssignment_3_1");
					put(grammarAccess.getOutgoingInformationDefAccess().getInformationListAssignment_5(), "rule__OutgoingInformationDef__InformationListAssignment_5");
					put(grammarAccess.getOutgoingInformationDefAccess().getInformationListAssignment_6_1(), "rule__OutgoingInformationDef__InformationListAssignment_6_1");
					put(grammarAccess.getInformationUsageAccess().getAnalysisFunctionAssignment_2(), "rule__InformationUsage__AnalysisFunctionAssignment_2");
					put(grammarAccess.getInformationUsageAccess().getInformationListAssignment_4(), "rule__InformationUsage__InformationListAssignment_4");
					put(grammarAccess.getInformationUsageAccess().getInformationListAssignment_5_1(), "rule__InformationUsage__InformationListAssignment_5_1");
					put(grammarAccess.getInformationCreationAccess().getAnalysisFunctionAssignment_2(), "rule__InformationCreation__AnalysisFunctionAssignment_2");
					put(grammarAccess.getInformationCreationAccess().getInformationListAssignment_4(), "rule__InformationCreation__InformationListAssignment_4");
					put(grammarAccess.getInformationCreationAccess().getInformationListAssignment_5_1(), "rule__InformationCreation__InformationListAssignment_5_1");
					put(grammarAccess.getAnalysisFunctionAccess().getNameAssignment_1(), "rule__AnalysisFunction__NameAssignment_1");
					put(grammarAccess.getInformationAccess().getNameAssignment_1(), "rule__Information__NameAssignment_1");
					put(grammarAccess.getHeadingSOAccess().getIdAssignment_5(), "rule__HeadingSO__IdAssignment_5");
					put(grammarAccess.getHeadingSOAccess().getParentAssignment_7_1(), "rule__HeadingSO__ParentAssignment_7_1");
					put(grammarAccess.getHeadingSOAccess().getTextAssignment_8(), "rule__HeadingSO__TextAssignment_8");
					put(grammarAccess.getReqPatSOAccess().getIdAssignment_5(), "rule__ReqPatSO__IdAssignment_5");
					put(grammarAccess.getReqPatSOAccess().getParentAssignment_7_1(), "rule__ReqPatSO__ParentAssignment_7_1");
					put(grammarAccess.getReqPatSOAccess().getRequirementPatternsAssignment_8(), "rule__ReqPatSO__RequirementPatternsAssignment_8");
					put(grammarAccess.getFreeTextSOAccess().getIdAssignment_5(), "rule__FreeTextSO__IdAssignment_5");
					put(grammarAccess.getFreeTextSOAccess().getParentAssignment_7_1(), "rule__FreeTextSO__ParentAssignment_7_1");
					put(grammarAccess.getFreeTextSOAccess().getFreeTextAssignment_8(), "rule__FreeTextSO__FreeTextAssignment_8");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			de.fraunhofer.iem.reqpat.demo.ui.contentassist.antlr.internal.InternalReqPatDemoParser typedParser = (de.fraunhofer.iem.reqpat.demo.ui.contentassist.antlr.internal.InternalReqPatDemoParser) parser;
			typedParser.entryRuleRoot();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public ReqPatDemoGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ReqPatDemoGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
