/*
 * generated by Xtext
 */
package de.fraunhofer.iem.reqpat.demo.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.documentation.IEObjectDocumentationProvider;
import org.eclipse.xtext.ui.editor.hover.IEObjectHoverProvider;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;

import de.fraunhofer.iem.reqpat.demo.ui.documentation.ReqPatDemoDocumentationProvider;
import de.fraunhofer.iem.reqpat.demo.ui.highlight.ReqPatDemoHighlightingConfiguration;
import de.fraunhofer.iem.reqpat.demo.ui.hover.ReqPatDemoHoverProvider;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ReqPatDemoUiModule extends
		de.fraunhofer.iem.reqpat.demo.ui.AbstractReqPatDemoUiModule {
	public ReqPatDemoUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	public Class<? extends IEObjectDocumentationProvider> bindIEObjectDocumentationProvider() {
		return ReqPatDemoDocumentationProvider.class;
	}

	public Class<? extends IEObjectHoverProvider> bindIEObjectHoverProvider() {
		return ReqPatDemoHoverProvider.class;
	}

	public Class<? extends IHighlightingConfiguration> bindIHighlightingConfiguration() {
		return ReqPatDemoHighlightingConfiguration.class;
	}
}
