/*
 * generated by Xtext
 */
package de.fraunhofer.iem.reqpat.demo.scoping;

import de.fraunhofer.iem.reqpat.core.scoping.ReqPatScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#scoping on
 * how and when to use it
 * 
 */
public class ReqPatDemoScopeProvider extends ReqPatScopeProvider {

}
