/*
* generated by Xtext
*/
package de.fraunhofer.iem.reqpat.core.parseTreeConstruction;

import org.eclipse.emf.ecore.*;
import org.eclipse.xtext.*;
import org.eclipse.xtext.parsetree.reconstr.IEObjectConsumer;
import org.eclipse.xtext.parsetree.reconstr.impl.AbstractParseTreeConstructor;

import de.fraunhofer.iem.reqpat.core.services.ReqPatGrammarAccess;

import com.google.inject.Inject;

@SuppressWarnings("all")
public class ReqPatParsetreeConstructor extends AbstractParseTreeConstructor {
		
	@Inject
	private ReqPatGrammarAccess grammarAccess;
	
	@Override
	protected AbstractToken getRootToken(IEObjectConsumer inst) {
		return new ThisRootNode(inst);	
	}
	
protected class ThisRootNode extends RootToken {
	public ThisRootNode(IEObjectConsumer inst) {
		super(inst);
	}
	
	@Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new Root_Group(this, this, 0, inst);
			case 1: return new SpecObj_Group(this, this, 1, inst);
			case 2: return new HeadingSO_Group(this, this, 2, inst);
			case 3: return new ReqPatSO_Group(this, this, 3, inst);
			case 4: return new FreeTextSO_Group(this, this, 4, inst);
			case 5: return new RequirementPattern_Group(this, this, 5, inst);
			default: return null;
		}	
	}	
}
	

/************ begin Rule Root ****************
 *
 * Root returns Specification:
 * 
 * 	{Specification} specObjects+=SpecObj+;
 *
 **/

// {Specification} specObjects+=SpecObj+
protected class Root_Group extends GroupToken {
	
	public Root_Group(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Group getGrammarElement() {
		return grammarAccess.getRootAccess().getGroup();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new Root_SpecObjectsAssignment_1(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

    @Override
	public IEObjectConsumer tryConsume() {
		if(getEObject().eClass() != grammarAccess.getRootAccess().getSpecificationAction_0().getType().getClassifier())
			return null;
		return eObjectConsumer;
	}

}

// {Specification}
protected class Root_SpecificationAction_0 extends ActionToken  {

	public Root_SpecificationAction_0(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Action getGrammarElement() {
		return grammarAccess.getRootAccess().getSpecificationAction_0();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			default: return lastRuleCallOrigin.createFollowerAfterReturn(this, index, index, inst);
		}	
	}

    @Override
	public IEObjectConsumer tryConsume() {
		if(!eObjectConsumer.isConsumed()) return null;
		return eObjectConsumer;
	}
}

// specObjects+=SpecObj+
protected class Root_SpecObjectsAssignment_1 extends AssignmentToken  {
	
	public Root_SpecObjectsAssignment_1(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Assignment getGrammarElement() {
		return grammarAccess.getRootAccess().getSpecObjectsAssignment_1();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new SpecObj_Group(this, this, 0, inst);
			default: return null;
		}	
	}

    @Override	
	public IEObjectConsumer tryConsume() {
		if((value = eObjectConsumer.getConsumable("specObjects",true)) == null) return null;
		IEObjectConsumer obj = eObjectConsumer.cloneAndConsume("specObjects");
		if(value instanceof EObject) { // org::eclipse::xtext::impl::RuleCallImpl
			IEObjectConsumer param = createEObjectConsumer((EObject)value);
			if(param.isInstanceOf(grammarAccess.getSpecObjRule().getType().getClassifier())) {
				type = AssignmentType.PARSER_RULE_CALL;
				element = grammarAccess.getRootAccess().getSpecObjectsSpecObjParserRuleCall_1_0(); 
				consumed = obj;
				return param;
			}
		}
		return null;
	}

    @Override
	public AbstractToken createFollowerAfterReturn(AbstractToken next,	int actIndex, int index, IEObjectConsumer inst) {
		if(value == inst.getEObject() && !inst.isConsumed()) return null;
		switch(index) {
			case 0: return new Root_SpecObjectsAssignment_1(lastRuleCallOrigin, next, actIndex, consumed);
			case 1: return new Root_SpecificationAction_0(lastRuleCallOrigin, next, actIndex, consumed);
			default: return null;
		}	
	}	
}


/************ end Rule Root ****************/


/************ begin Rule SpecObj ****************
 *
 * SpecObj returns SpecObject:
 * 
 * 	SPECOBJECTDELIMITERLEFT (HeadingSO | ReqPatSO | FreeTextSO) SPECOBJECTDELIMITERRIGHT;
 *
 **/

// SPECOBJECTDELIMITERLEFT (HeadingSO | ReqPatSO | FreeTextSO) SPECOBJECTDELIMITERRIGHT
protected class SpecObj_Group extends GroupToken {
	
	public SpecObj_Group(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Group getGrammarElement() {
		return grammarAccess.getSpecObjAccess().getGroup();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new SpecObj_SPECOBJECTDELIMITERRIGHTTerminalRuleCall_2(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

    @Override
	public IEObjectConsumer tryConsume() {
		if(getEObject().eClass() != grammarAccess.getFreeTextSOAccess().getFreeTextSpecObjectAction_0().getType().getClassifier() && 
		   getEObject().eClass() != grammarAccess.getHeadingSOAccess().getHeadingSpecObjectAction_0().getType().getClassifier() && 
		   getEObject().eClass() != grammarAccess.getReqPatSOAccess().getRequirementPatternSpecObjectAction_0().getType().getClassifier())
			return null;
		return eObjectConsumer;
	}

}

// SPECOBJECTDELIMITERLEFT
protected class SpecObj_SPECOBJECTDELIMITERLEFTTerminalRuleCall_0 extends UnassignedTextToken {

	public SpecObj_SPECOBJECTDELIMITERLEFTTerminalRuleCall_0(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public RuleCall getGrammarElement() {
		return grammarAccess.getSpecObjAccess().getSPECOBJECTDELIMITERLEFTTerminalRuleCall_0();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			default: return lastRuleCallOrigin.createFollowerAfterReturn(this, index, index, inst);
		}	
	}

}

// HeadingSO | ReqPatSO | FreeTextSO
protected class SpecObj_Alternatives_1 extends AlternativesToken {

	public SpecObj_Alternatives_1(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Alternatives getGrammarElement() {
		return grammarAccess.getSpecObjAccess().getAlternatives_1();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new SpecObj_HeadingSOParserRuleCall_1_0(lastRuleCallOrigin, this, 0, inst);
			case 1: return new SpecObj_ReqPatSOParserRuleCall_1_1(lastRuleCallOrigin, this, 1, inst);
			case 2: return new SpecObj_FreeTextSOParserRuleCall_1_2(lastRuleCallOrigin, this, 2, inst);
			default: return null;
		}	
	}

}

// HeadingSO
protected class SpecObj_HeadingSOParserRuleCall_1_0 extends RuleCallToken {
	
	public SpecObj_HeadingSOParserRuleCall_1_0(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public RuleCall getGrammarElement() {
		return grammarAccess.getSpecObjAccess().getHeadingSOParserRuleCall_1_0();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new HeadingSO_Group(this, this, 0, inst);
			default: return null;
		}	
	}

    @Override
	public IEObjectConsumer tryConsume() {
		if(getEObject().eClass() != grammarAccess.getHeadingSOAccess().getHeadingSpecObjectAction_0().getType().getClassifier())
			return null;
		if(checkForRecursion(HeadingSO_Group.class, eObjectConsumer)) return null;
		return eObjectConsumer;
	}
	
    @Override
	public AbstractToken createFollowerAfterReturn(AbstractToken next,	int actIndex, int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new SpecObj_SPECOBJECTDELIMITERLEFTTerminalRuleCall_0(lastRuleCallOrigin, next, actIndex, inst);
			default: return null;
		}	
	}	
}

// ReqPatSO
protected class SpecObj_ReqPatSOParserRuleCall_1_1 extends RuleCallToken {
	
	public SpecObj_ReqPatSOParserRuleCall_1_1(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public RuleCall getGrammarElement() {
		return grammarAccess.getSpecObjAccess().getReqPatSOParserRuleCall_1_1();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new ReqPatSO_Group(this, this, 0, inst);
			default: return null;
		}	
	}

    @Override
	public IEObjectConsumer tryConsume() {
		if(getEObject().eClass() != grammarAccess.getReqPatSOAccess().getRequirementPatternSpecObjectAction_0().getType().getClassifier())
			return null;
		if(checkForRecursion(ReqPatSO_Group.class, eObjectConsumer)) return null;
		return eObjectConsumer;
	}
	
    @Override
	public AbstractToken createFollowerAfterReturn(AbstractToken next,	int actIndex, int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new SpecObj_SPECOBJECTDELIMITERLEFTTerminalRuleCall_0(lastRuleCallOrigin, next, actIndex, inst);
			default: return null;
		}	
	}	
}

// FreeTextSO
protected class SpecObj_FreeTextSOParserRuleCall_1_2 extends RuleCallToken {
	
	public SpecObj_FreeTextSOParserRuleCall_1_2(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public RuleCall getGrammarElement() {
		return grammarAccess.getSpecObjAccess().getFreeTextSOParserRuleCall_1_2();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new FreeTextSO_Group(this, this, 0, inst);
			default: return null;
		}	
	}

    @Override
	public IEObjectConsumer tryConsume() {
		if(getEObject().eClass() != grammarAccess.getFreeTextSOAccess().getFreeTextSpecObjectAction_0().getType().getClassifier())
			return null;
		if(checkForRecursion(FreeTextSO_Group.class, eObjectConsumer)) return null;
		return eObjectConsumer;
	}
	
    @Override
	public AbstractToken createFollowerAfterReturn(AbstractToken next,	int actIndex, int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new SpecObj_SPECOBJECTDELIMITERLEFTTerminalRuleCall_0(lastRuleCallOrigin, next, actIndex, inst);
			default: return null;
		}	
	}	
}


// SPECOBJECTDELIMITERRIGHT
protected class SpecObj_SPECOBJECTDELIMITERRIGHTTerminalRuleCall_2 extends UnassignedTextToken {

	public SpecObj_SPECOBJECTDELIMITERRIGHTTerminalRuleCall_2(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public RuleCall getGrammarElement() {
		return grammarAccess.getSpecObjAccess().getSPECOBJECTDELIMITERRIGHTTerminalRuleCall_2();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new SpecObj_Alternatives_1(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

}


/************ end Rule SpecObj ****************/


/************ begin Rule HeadingSO ****************
 *
 * HeadingSO returns HeadingSpecObject:
 * 
 * 	{HeadingSpecObject} PARAMDELIMITERLEFT "H" PARAMDELIMITERRIGHT PARAMDELIMITERLEFT id=ID PARAMDELIMITERRIGHT
 * 
 * 	(PARAMDELIMITERLEFT parent=STRING PARAMDELIMITERRIGHT)? text=STRING;
 *
 **/

// {HeadingSpecObject} PARAMDELIMITERLEFT "H" PARAMDELIMITERRIGHT PARAMDELIMITERLEFT id=ID PARAMDELIMITERRIGHT
// 
// (PARAMDELIMITERLEFT parent=STRING PARAMDELIMITERRIGHT)? text=STRING
protected class HeadingSO_Group extends GroupToken {
	
	public HeadingSO_Group(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Group getGrammarElement() {
		return grammarAccess.getHeadingSOAccess().getGroup();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new HeadingSO_TextAssignment_8(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

    @Override
	public IEObjectConsumer tryConsume() {
		if(getEObject().eClass() != grammarAccess.getHeadingSOAccess().getHeadingSpecObjectAction_0().getType().getClassifier())
			return null;
		return eObjectConsumer;
	}

}

// {HeadingSpecObject}
protected class HeadingSO_HeadingSpecObjectAction_0 extends ActionToken  {

	public HeadingSO_HeadingSpecObjectAction_0(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Action getGrammarElement() {
		return grammarAccess.getHeadingSOAccess().getHeadingSpecObjectAction_0();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			default: return lastRuleCallOrigin.createFollowerAfterReturn(this, index, index, inst);
		}	
	}

    @Override
	public IEObjectConsumer tryConsume() {
		if(!eObjectConsumer.isConsumed()) return null;
		return eObjectConsumer;
	}
}

// PARAMDELIMITERLEFT
protected class HeadingSO_PARAMDELIMITERLEFTTerminalRuleCall_1 extends UnassignedTextToken {

	public HeadingSO_PARAMDELIMITERLEFTTerminalRuleCall_1(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public RuleCall getGrammarElement() {
		return grammarAccess.getHeadingSOAccess().getPARAMDELIMITERLEFTTerminalRuleCall_1();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new HeadingSO_HeadingSpecObjectAction_0(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

}

// "H"
protected class HeadingSO_HKeyword_2 extends KeywordToken  {
	
	public HeadingSO_HKeyword_2(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Keyword getGrammarElement() {
		return grammarAccess.getHeadingSOAccess().getHKeyword_2();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new HeadingSO_PARAMDELIMITERLEFTTerminalRuleCall_1(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

}

// PARAMDELIMITERRIGHT
protected class HeadingSO_PARAMDELIMITERRIGHTTerminalRuleCall_3 extends UnassignedTextToken {

	public HeadingSO_PARAMDELIMITERRIGHTTerminalRuleCall_3(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public RuleCall getGrammarElement() {
		return grammarAccess.getHeadingSOAccess().getPARAMDELIMITERRIGHTTerminalRuleCall_3();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new HeadingSO_HKeyword_2(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

}

// PARAMDELIMITERLEFT
protected class HeadingSO_PARAMDELIMITERLEFTTerminalRuleCall_4 extends UnassignedTextToken {

	public HeadingSO_PARAMDELIMITERLEFTTerminalRuleCall_4(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public RuleCall getGrammarElement() {
		return grammarAccess.getHeadingSOAccess().getPARAMDELIMITERLEFTTerminalRuleCall_4();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new HeadingSO_PARAMDELIMITERRIGHTTerminalRuleCall_3(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

}

// id=ID
protected class HeadingSO_IdAssignment_5 extends AssignmentToken  {
	
	public HeadingSO_IdAssignment_5(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Assignment getGrammarElement() {
		return grammarAccess.getHeadingSOAccess().getIdAssignment_5();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new HeadingSO_PARAMDELIMITERLEFTTerminalRuleCall_4(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

    @Override	
	public IEObjectConsumer tryConsume() {
		if((value = eObjectConsumer.getConsumable("id",true)) == null) return null;
		IEObjectConsumer obj = eObjectConsumer.cloneAndConsume("id");
		if(valueSerializer.isValid(obj.getEObject(), grammarAccess.getHeadingSOAccess().getIdIDTerminalRuleCall_5_0(), value, null)) {
			type = AssignmentType.TERMINAL_RULE_CALL;
			element = grammarAccess.getHeadingSOAccess().getIdIDTerminalRuleCall_5_0();
			return obj;
		}
		return null;
	}

}

// PARAMDELIMITERRIGHT
protected class HeadingSO_PARAMDELIMITERRIGHTTerminalRuleCall_6 extends UnassignedTextToken {

	public HeadingSO_PARAMDELIMITERRIGHTTerminalRuleCall_6(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public RuleCall getGrammarElement() {
		return grammarAccess.getHeadingSOAccess().getPARAMDELIMITERRIGHTTerminalRuleCall_6();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new HeadingSO_IdAssignment_5(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

}

// (PARAMDELIMITERLEFT parent=STRING PARAMDELIMITERRIGHT)?
protected class HeadingSO_Group_7 extends GroupToken {
	
	public HeadingSO_Group_7(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Group getGrammarElement() {
		return grammarAccess.getHeadingSOAccess().getGroup_7();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new HeadingSO_PARAMDELIMITERRIGHTTerminalRuleCall_7_2(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

}

// PARAMDELIMITERLEFT
protected class HeadingSO_PARAMDELIMITERLEFTTerminalRuleCall_7_0 extends UnassignedTextToken {

	public HeadingSO_PARAMDELIMITERLEFTTerminalRuleCall_7_0(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public RuleCall getGrammarElement() {
		return grammarAccess.getHeadingSOAccess().getPARAMDELIMITERLEFTTerminalRuleCall_7_0();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new HeadingSO_PARAMDELIMITERRIGHTTerminalRuleCall_6(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

}

// parent=STRING
protected class HeadingSO_ParentAssignment_7_1 extends AssignmentToken  {
	
	public HeadingSO_ParentAssignment_7_1(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Assignment getGrammarElement() {
		return grammarAccess.getHeadingSOAccess().getParentAssignment_7_1();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new HeadingSO_PARAMDELIMITERLEFTTerminalRuleCall_7_0(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

    @Override	
	public IEObjectConsumer tryConsume() {
		if((value = eObjectConsumer.getConsumable("parent",false)) == null) return null;
		IEObjectConsumer obj = eObjectConsumer.cloneAndConsume("parent");
		if(valueSerializer.isValid(obj.getEObject(), grammarAccess.getHeadingSOAccess().getParentSTRINGTerminalRuleCall_7_1_0(), value, null)) {
			type = AssignmentType.TERMINAL_RULE_CALL;
			element = grammarAccess.getHeadingSOAccess().getParentSTRINGTerminalRuleCall_7_1_0();
			return obj;
		}
		return null;
	}

}

// PARAMDELIMITERRIGHT
protected class HeadingSO_PARAMDELIMITERRIGHTTerminalRuleCall_7_2 extends UnassignedTextToken {

	public HeadingSO_PARAMDELIMITERRIGHTTerminalRuleCall_7_2(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public RuleCall getGrammarElement() {
		return grammarAccess.getHeadingSOAccess().getPARAMDELIMITERRIGHTTerminalRuleCall_7_2();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new HeadingSO_ParentAssignment_7_1(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

}


// text=STRING
protected class HeadingSO_TextAssignment_8 extends AssignmentToken  {
	
	public HeadingSO_TextAssignment_8(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Assignment getGrammarElement() {
		return grammarAccess.getHeadingSOAccess().getTextAssignment_8();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new HeadingSO_Group_7(lastRuleCallOrigin, this, 0, inst);
			case 1: return new HeadingSO_PARAMDELIMITERRIGHTTerminalRuleCall_6(lastRuleCallOrigin, this, 1, inst);
			default: return null;
		}	
	}

    @Override	
	public IEObjectConsumer tryConsume() {
		if((value = eObjectConsumer.getConsumable("text",true)) == null) return null;
		IEObjectConsumer obj = eObjectConsumer.cloneAndConsume("text");
		if(valueSerializer.isValid(obj.getEObject(), grammarAccess.getHeadingSOAccess().getTextSTRINGTerminalRuleCall_8_0(), value, null)) {
			type = AssignmentType.TERMINAL_RULE_CALL;
			element = grammarAccess.getHeadingSOAccess().getTextSTRINGTerminalRuleCall_8_0();
			return obj;
		}
		return null;
	}

}


/************ end Rule HeadingSO ****************/


/************ begin Rule ReqPatSO ****************
 *
 * ReqPatSO returns RequirementPatternSpecObject:
 * 
 * 	{RequirementPatternSpecObject} PARAMDELIMITERLEFT "RP" PARAMDELIMITERRIGHT PARAMDELIMITERLEFT id=ID
 * 
 * 	PARAMDELIMITERRIGHT (PARAMDELIMITERLEFT parent=STRING PARAMDELIMITERRIGHT)? requirementPatterns+=RequirementPattern+;
 *
 **/

// {RequirementPatternSpecObject} PARAMDELIMITERLEFT "RP" PARAMDELIMITERRIGHT PARAMDELIMITERLEFT id=ID PARAMDELIMITERRIGHT
// 
// (PARAMDELIMITERLEFT parent=STRING PARAMDELIMITERRIGHT)? requirementPatterns+=RequirementPattern+
protected class ReqPatSO_Group extends GroupToken {
	
	public ReqPatSO_Group(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Group getGrammarElement() {
		return grammarAccess.getReqPatSOAccess().getGroup();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new ReqPatSO_RequirementPatternsAssignment_8(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

    @Override
	public IEObjectConsumer tryConsume() {
		if(getEObject().eClass() != grammarAccess.getReqPatSOAccess().getRequirementPatternSpecObjectAction_0().getType().getClassifier())
			return null;
		return eObjectConsumer;
	}

}

// {RequirementPatternSpecObject}
protected class ReqPatSO_RequirementPatternSpecObjectAction_0 extends ActionToken  {

	public ReqPatSO_RequirementPatternSpecObjectAction_0(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Action getGrammarElement() {
		return grammarAccess.getReqPatSOAccess().getRequirementPatternSpecObjectAction_0();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			default: return lastRuleCallOrigin.createFollowerAfterReturn(this, index, index, inst);
		}	
	}

    @Override
	public IEObjectConsumer tryConsume() {
		if(!eObjectConsumer.isConsumed()) return null;
		return eObjectConsumer;
	}
}

// PARAMDELIMITERLEFT
protected class ReqPatSO_PARAMDELIMITERLEFTTerminalRuleCall_1 extends UnassignedTextToken {

	public ReqPatSO_PARAMDELIMITERLEFTTerminalRuleCall_1(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public RuleCall getGrammarElement() {
		return grammarAccess.getReqPatSOAccess().getPARAMDELIMITERLEFTTerminalRuleCall_1();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new ReqPatSO_RequirementPatternSpecObjectAction_0(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

}

// "RP"
protected class ReqPatSO_RPKeyword_2 extends KeywordToken  {
	
	public ReqPatSO_RPKeyword_2(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Keyword getGrammarElement() {
		return grammarAccess.getReqPatSOAccess().getRPKeyword_2();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new ReqPatSO_PARAMDELIMITERLEFTTerminalRuleCall_1(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

}

// PARAMDELIMITERRIGHT
protected class ReqPatSO_PARAMDELIMITERRIGHTTerminalRuleCall_3 extends UnassignedTextToken {

	public ReqPatSO_PARAMDELIMITERRIGHTTerminalRuleCall_3(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public RuleCall getGrammarElement() {
		return grammarAccess.getReqPatSOAccess().getPARAMDELIMITERRIGHTTerminalRuleCall_3();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new ReqPatSO_RPKeyword_2(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

}

// PARAMDELIMITERLEFT
protected class ReqPatSO_PARAMDELIMITERLEFTTerminalRuleCall_4 extends UnassignedTextToken {

	public ReqPatSO_PARAMDELIMITERLEFTTerminalRuleCall_4(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public RuleCall getGrammarElement() {
		return grammarAccess.getReqPatSOAccess().getPARAMDELIMITERLEFTTerminalRuleCall_4();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new ReqPatSO_PARAMDELIMITERRIGHTTerminalRuleCall_3(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

}

// id=ID
protected class ReqPatSO_IdAssignment_5 extends AssignmentToken  {
	
	public ReqPatSO_IdAssignment_5(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Assignment getGrammarElement() {
		return grammarAccess.getReqPatSOAccess().getIdAssignment_5();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new ReqPatSO_PARAMDELIMITERLEFTTerminalRuleCall_4(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

    @Override	
	public IEObjectConsumer tryConsume() {
		if((value = eObjectConsumer.getConsumable("id",true)) == null) return null;
		IEObjectConsumer obj = eObjectConsumer.cloneAndConsume("id");
		if(valueSerializer.isValid(obj.getEObject(), grammarAccess.getReqPatSOAccess().getIdIDTerminalRuleCall_5_0(), value, null)) {
			type = AssignmentType.TERMINAL_RULE_CALL;
			element = grammarAccess.getReqPatSOAccess().getIdIDTerminalRuleCall_5_0();
			return obj;
		}
		return null;
	}

}

// PARAMDELIMITERRIGHT
protected class ReqPatSO_PARAMDELIMITERRIGHTTerminalRuleCall_6 extends UnassignedTextToken {

	public ReqPatSO_PARAMDELIMITERRIGHTTerminalRuleCall_6(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public RuleCall getGrammarElement() {
		return grammarAccess.getReqPatSOAccess().getPARAMDELIMITERRIGHTTerminalRuleCall_6();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new ReqPatSO_IdAssignment_5(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

}

// (PARAMDELIMITERLEFT parent=STRING PARAMDELIMITERRIGHT)?
protected class ReqPatSO_Group_7 extends GroupToken {
	
	public ReqPatSO_Group_7(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Group getGrammarElement() {
		return grammarAccess.getReqPatSOAccess().getGroup_7();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new ReqPatSO_PARAMDELIMITERRIGHTTerminalRuleCall_7_2(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

}

// PARAMDELIMITERLEFT
protected class ReqPatSO_PARAMDELIMITERLEFTTerminalRuleCall_7_0 extends UnassignedTextToken {

	public ReqPatSO_PARAMDELIMITERLEFTTerminalRuleCall_7_0(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public RuleCall getGrammarElement() {
		return grammarAccess.getReqPatSOAccess().getPARAMDELIMITERLEFTTerminalRuleCall_7_0();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new ReqPatSO_PARAMDELIMITERRIGHTTerminalRuleCall_6(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

}

// parent=STRING
protected class ReqPatSO_ParentAssignment_7_1 extends AssignmentToken  {
	
	public ReqPatSO_ParentAssignment_7_1(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Assignment getGrammarElement() {
		return grammarAccess.getReqPatSOAccess().getParentAssignment_7_1();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new ReqPatSO_PARAMDELIMITERLEFTTerminalRuleCall_7_0(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

    @Override	
	public IEObjectConsumer tryConsume() {
		if((value = eObjectConsumer.getConsumable("parent",false)) == null) return null;
		IEObjectConsumer obj = eObjectConsumer.cloneAndConsume("parent");
		if(valueSerializer.isValid(obj.getEObject(), grammarAccess.getReqPatSOAccess().getParentSTRINGTerminalRuleCall_7_1_0(), value, null)) {
			type = AssignmentType.TERMINAL_RULE_CALL;
			element = grammarAccess.getReqPatSOAccess().getParentSTRINGTerminalRuleCall_7_1_0();
			return obj;
		}
		return null;
	}

}

// PARAMDELIMITERRIGHT
protected class ReqPatSO_PARAMDELIMITERRIGHTTerminalRuleCall_7_2 extends UnassignedTextToken {

	public ReqPatSO_PARAMDELIMITERRIGHTTerminalRuleCall_7_2(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public RuleCall getGrammarElement() {
		return grammarAccess.getReqPatSOAccess().getPARAMDELIMITERRIGHTTerminalRuleCall_7_2();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new ReqPatSO_ParentAssignment_7_1(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

}


// requirementPatterns+=RequirementPattern+
protected class ReqPatSO_RequirementPatternsAssignment_8 extends AssignmentToken  {
	
	public ReqPatSO_RequirementPatternsAssignment_8(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Assignment getGrammarElement() {
		return grammarAccess.getReqPatSOAccess().getRequirementPatternsAssignment_8();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new RequirementPattern_Group(this, this, 0, inst);
			default: return null;
		}	
	}

    @Override	
	public IEObjectConsumer tryConsume() {
		if((value = eObjectConsumer.getConsumable("requirementPatterns",true)) == null) return null;
		IEObjectConsumer obj = eObjectConsumer.cloneAndConsume("requirementPatterns");
		if(value instanceof EObject) { // org::eclipse::xtext::impl::RuleCallImpl
			IEObjectConsumer param = createEObjectConsumer((EObject)value);
			if(param.isInstanceOf(grammarAccess.getRequirementPatternRule().getType().getClassifier())) {
				type = AssignmentType.PARSER_RULE_CALL;
				element = grammarAccess.getReqPatSOAccess().getRequirementPatternsRequirementPatternParserRuleCall_8_0(); 
				consumed = obj;
				return param;
			}
		}
		return null;
	}

    @Override
	public AbstractToken createFollowerAfterReturn(AbstractToken next,	int actIndex, int index, IEObjectConsumer inst) {
		if(value == inst.getEObject() && !inst.isConsumed()) return null;
		switch(index) {
			case 0: return new ReqPatSO_RequirementPatternsAssignment_8(lastRuleCallOrigin, next, actIndex, consumed);
			case 1: return new ReqPatSO_Group_7(lastRuleCallOrigin, next, actIndex, consumed);
			case 2: return new ReqPatSO_PARAMDELIMITERRIGHTTerminalRuleCall_6(lastRuleCallOrigin, next, actIndex, consumed);
			default: return null;
		}	
	}	
}


/************ end Rule ReqPatSO ****************/


/************ begin Rule FreeTextSO ****************
 *
 * FreeTextSO returns FreeTextSpecObject:
 * 
 * 	{FreeTextSpecObject} PARAMDELIMITERLEFT "F" PARAMDELIMITERRIGHT PARAMDELIMITERLEFT id=ID PARAMDELIMITERRIGHT
 * 
 * 	(PARAMDELIMITERLEFT parent=STRING PARAMDELIMITERRIGHT)? freeText=STRING?;
 *
 **/

// {FreeTextSpecObject} PARAMDELIMITERLEFT "F" PARAMDELIMITERRIGHT PARAMDELIMITERLEFT id=ID PARAMDELIMITERRIGHT
// 
// (PARAMDELIMITERLEFT parent=STRING PARAMDELIMITERRIGHT)? freeText=STRING?
protected class FreeTextSO_Group extends GroupToken {
	
	public FreeTextSO_Group(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Group getGrammarElement() {
		return grammarAccess.getFreeTextSOAccess().getGroup();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new FreeTextSO_FreeTextAssignment_8(lastRuleCallOrigin, this, 0, inst);
			case 1: return new FreeTextSO_Group_7(lastRuleCallOrigin, this, 1, inst);
			case 2: return new FreeTextSO_PARAMDELIMITERRIGHTTerminalRuleCall_6(lastRuleCallOrigin, this, 2, inst);
			default: return null;
		}	
	}

    @Override
	public IEObjectConsumer tryConsume() {
		if(getEObject().eClass() != grammarAccess.getFreeTextSOAccess().getFreeTextSpecObjectAction_0().getType().getClassifier())
			return null;
		return eObjectConsumer;
	}

}

// {FreeTextSpecObject}
protected class FreeTextSO_FreeTextSpecObjectAction_0 extends ActionToken  {

	public FreeTextSO_FreeTextSpecObjectAction_0(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Action getGrammarElement() {
		return grammarAccess.getFreeTextSOAccess().getFreeTextSpecObjectAction_0();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			default: return lastRuleCallOrigin.createFollowerAfterReturn(this, index, index, inst);
		}	
	}

    @Override
	public IEObjectConsumer tryConsume() {
		if(!eObjectConsumer.isConsumed()) return null;
		return eObjectConsumer;
	}
}

// PARAMDELIMITERLEFT
protected class FreeTextSO_PARAMDELIMITERLEFTTerminalRuleCall_1 extends UnassignedTextToken {

	public FreeTextSO_PARAMDELIMITERLEFTTerminalRuleCall_1(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public RuleCall getGrammarElement() {
		return grammarAccess.getFreeTextSOAccess().getPARAMDELIMITERLEFTTerminalRuleCall_1();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new FreeTextSO_FreeTextSpecObjectAction_0(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

}

// "F"
protected class FreeTextSO_FKeyword_2 extends KeywordToken  {
	
	public FreeTextSO_FKeyword_2(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Keyword getGrammarElement() {
		return grammarAccess.getFreeTextSOAccess().getFKeyword_2();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new FreeTextSO_PARAMDELIMITERLEFTTerminalRuleCall_1(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

}

// PARAMDELIMITERRIGHT
protected class FreeTextSO_PARAMDELIMITERRIGHTTerminalRuleCall_3 extends UnassignedTextToken {

	public FreeTextSO_PARAMDELIMITERRIGHTTerminalRuleCall_3(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public RuleCall getGrammarElement() {
		return grammarAccess.getFreeTextSOAccess().getPARAMDELIMITERRIGHTTerminalRuleCall_3();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new FreeTextSO_FKeyword_2(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

}

// PARAMDELIMITERLEFT
protected class FreeTextSO_PARAMDELIMITERLEFTTerminalRuleCall_4 extends UnassignedTextToken {

	public FreeTextSO_PARAMDELIMITERLEFTTerminalRuleCall_4(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public RuleCall getGrammarElement() {
		return grammarAccess.getFreeTextSOAccess().getPARAMDELIMITERLEFTTerminalRuleCall_4();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new FreeTextSO_PARAMDELIMITERRIGHTTerminalRuleCall_3(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

}

// id=ID
protected class FreeTextSO_IdAssignment_5 extends AssignmentToken  {
	
	public FreeTextSO_IdAssignment_5(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Assignment getGrammarElement() {
		return grammarAccess.getFreeTextSOAccess().getIdAssignment_5();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new FreeTextSO_PARAMDELIMITERLEFTTerminalRuleCall_4(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

    @Override	
	public IEObjectConsumer tryConsume() {
		if((value = eObjectConsumer.getConsumable("id",true)) == null) return null;
		IEObjectConsumer obj = eObjectConsumer.cloneAndConsume("id");
		if(valueSerializer.isValid(obj.getEObject(), grammarAccess.getFreeTextSOAccess().getIdIDTerminalRuleCall_5_0(), value, null)) {
			type = AssignmentType.TERMINAL_RULE_CALL;
			element = grammarAccess.getFreeTextSOAccess().getIdIDTerminalRuleCall_5_0();
			return obj;
		}
		return null;
	}

}

// PARAMDELIMITERRIGHT
protected class FreeTextSO_PARAMDELIMITERRIGHTTerminalRuleCall_6 extends UnassignedTextToken {

	public FreeTextSO_PARAMDELIMITERRIGHTTerminalRuleCall_6(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public RuleCall getGrammarElement() {
		return grammarAccess.getFreeTextSOAccess().getPARAMDELIMITERRIGHTTerminalRuleCall_6();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new FreeTextSO_IdAssignment_5(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

}

// (PARAMDELIMITERLEFT parent=STRING PARAMDELIMITERRIGHT)?
protected class FreeTextSO_Group_7 extends GroupToken {
	
	public FreeTextSO_Group_7(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Group getGrammarElement() {
		return grammarAccess.getFreeTextSOAccess().getGroup_7();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new FreeTextSO_PARAMDELIMITERRIGHTTerminalRuleCall_7_2(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

}

// PARAMDELIMITERLEFT
protected class FreeTextSO_PARAMDELIMITERLEFTTerminalRuleCall_7_0 extends UnassignedTextToken {

	public FreeTextSO_PARAMDELIMITERLEFTTerminalRuleCall_7_0(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public RuleCall getGrammarElement() {
		return grammarAccess.getFreeTextSOAccess().getPARAMDELIMITERLEFTTerminalRuleCall_7_0();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new FreeTextSO_PARAMDELIMITERRIGHTTerminalRuleCall_6(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

}

// parent=STRING
protected class FreeTextSO_ParentAssignment_7_1 extends AssignmentToken  {
	
	public FreeTextSO_ParentAssignment_7_1(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Assignment getGrammarElement() {
		return grammarAccess.getFreeTextSOAccess().getParentAssignment_7_1();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new FreeTextSO_PARAMDELIMITERLEFTTerminalRuleCall_7_0(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

    @Override	
	public IEObjectConsumer tryConsume() {
		if((value = eObjectConsumer.getConsumable("parent",false)) == null) return null;
		IEObjectConsumer obj = eObjectConsumer.cloneAndConsume("parent");
		if(valueSerializer.isValid(obj.getEObject(), grammarAccess.getFreeTextSOAccess().getParentSTRINGTerminalRuleCall_7_1_0(), value, null)) {
			type = AssignmentType.TERMINAL_RULE_CALL;
			element = grammarAccess.getFreeTextSOAccess().getParentSTRINGTerminalRuleCall_7_1_0();
			return obj;
		}
		return null;
	}

}

// PARAMDELIMITERRIGHT
protected class FreeTextSO_PARAMDELIMITERRIGHTTerminalRuleCall_7_2 extends UnassignedTextToken {

	public FreeTextSO_PARAMDELIMITERRIGHTTerminalRuleCall_7_2(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public RuleCall getGrammarElement() {
		return grammarAccess.getFreeTextSOAccess().getPARAMDELIMITERRIGHTTerminalRuleCall_7_2();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new FreeTextSO_ParentAssignment_7_1(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

}


// freeText=STRING?
protected class FreeTextSO_FreeTextAssignment_8 extends AssignmentToken  {
	
	public FreeTextSO_FreeTextAssignment_8(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Assignment getGrammarElement() {
		return grammarAccess.getFreeTextSOAccess().getFreeTextAssignment_8();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new FreeTextSO_Group_7(lastRuleCallOrigin, this, 0, inst);
			case 1: return new FreeTextSO_PARAMDELIMITERRIGHTTerminalRuleCall_6(lastRuleCallOrigin, this, 1, inst);
			default: return null;
		}	
	}

    @Override	
	public IEObjectConsumer tryConsume() {
		if((value = eObjectConsumer.getConsumable("freeText",false)) == null) return null;
		IEObjectConsumer obj = eObjectConsumer.cloneAndConsume("freeText");
		if(valueSerializer.isValid(obj.getEObject(), grammarAccess.getFreeTextSOAccess().getFreeTextSTRINGTerminalRuleCall_8_0(), value, null)) {
			type = AssignmentType.TERMINAL_RULE_CALL;
			element = grammarAccess.getFreeTextSOAccess().getFreeTextSTRINGTerminalRuleCall_8_0();
			return obj;
		}
		return null;
	}

}


/************ end Rule FreeTextSO ****************/


/************ begin Rule RequirementPattern ****************
 *
 * RequirementPattern:
 * 
 * 	{RequirementPattern} "This is a sample requirement pattern.";
 *
 **/

// {RequirementPattern} "This is a sample requirement pattern."
protected class RequirementPattern_Group extends GroupToken {
	
	public RequirementPattern_Group(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Group getGrammarElement() {
		return grammarAccess.getRequirementPatternAccess().getGroup();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new RequirementPattern_ThisIsASampleRequirementPatternKeyword_1(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

    @Override
	public IEObjectConsumer tryConsume() {
		if(getEObject().eClass() != grammarAccess.getRequirementPatternAccess().getRequirementPatternAction_0().getType().getClassifier())
			return null;
		return eObjectConsumer;
	}

}

// {RequirementPattern}
protected class RequirementPattern_RequirementPatternAction_0 extends ActionToken  {

	public RequirementPattern_RequirementPatternAction_0(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Action getGrammarElement() {
		return grammarAccess.getRequirementPatternAccess().getRequirementPatternAction_0();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			default: return lastRuleCallOrigin.createFollowerAfterReturn(this, index, index, inst);
		}	
	}

    @Override
	public IEObjectConsumer tryConsume() {
		if(!eObjectConsumer.isConsumed()) return null;
		return eObjectConsumer;
	}
}

// "This is a sample requirement pattern."
protected class RequirementPattern_ThisIsASampleRequirementPatternKeyword_1 extends KeywordToken  {
	
	public RequirementPattern_ThisIsASampleRequirementPatternKeyword_1(AbstractToken lastRuleCallOrigin, AbstractToken next, int transitionIndex, IEObjectConsumer eObjectConsumer) {
		super(lastRuleCallOrigin, next, transitionIndex, eObjectConsumer);
	}
	
	@Override
	public Keyword getGrammarElement() {
		return grammarAccess.getRequirementPatternAccess().getThisIsASampleRequirementPatternKeyword_1();
	}

    @Override
	public AbstractToken createFollower(int index, IEObjectConsumer inst) {
		switch(index) {
			case 0: return new RequirementPattern_RequirementPatternAction_0(lastRuleCallOrigin, this, 0, inst);
			default: return null;
		}	
	}

}


/************ end Rule RequirementPattern ****************/

}
