/*
* generated by Xtext
*/
package de.fraunhofer.iem.reqpat.core.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class ReqPatOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
